name: Build & Publish Docker images
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish docker images
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: cfbsks/mst
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}